# Generated by Django 4.2.1 on 2023-07-05 08:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('med_test1_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mob_no', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('created_time', models.TimeField(default=django.utils.timezone.now)),
                ('med_test1_report', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='med_test1_app.med_test1_report')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('med_test1', models.IntegerField(null=True)),
                ('med_test2', models.IntegerField(null=True)),
                ('med_test3', models.IntegerField(null=True)),
                ('med_test4', models.IntegerField(null=True)),
                ('done_by', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('created_time', models.TimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='patient_app.patient')),
            ],
        ),
    ]
