# Generated by Django 4.2.1 on 2023-07-06 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_test1_app', '0001_initial'),
        ('patient_app', '0002_alter_receipt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constants',
            name='id',
        ),
        migrations.AlterField(
            model_name='constants',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='constants',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='med_test1_report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med_test1_report', to='med_test1_app.med_test1_report'),
        ),
    ]
