# Generated by Django 4.2.1 on 2023-07-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_remove_constants_id_alter_constants_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constants',
            new_name='Constant',
        ),
    ]
