# Generated by Django 4.2.1 on 2023-07-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0004_rename_constants_constant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constant',
        ),
        migrations.AddField(
            model_name='patient',
            name='med_test1',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
