# Generated by Django 4.2.1 on 2023-07-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_delete_constant_patient_med_test1_delete_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='med_test2_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='med_test2_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='med_test2_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='med_test2_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='med_test2_5',
            field=models.BooleanField(default=False),
        ),
    ]
