from django.db import models
from django.utils import timezone

# Create your models here.

# from patient_app.models import Patient

# many to one relation -> one patient may have many reports but one report will have only one patient

class Med_test1_report(models.Model):
    """
    Model representing an Echo report.
    """
    # patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='EchoReport')
    # patient=models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='med_test1_report')
    id=models.AutoField(primary_key=True)
    reffered_by=models.CharField(max_length=200, null=True)
    validated_by=models.CharField(max_length=200, null=True)
    created_date=models.DateField(default=timezone.now)
    lab_no=models.IntegerField(null=True)

    t1_1=models.TextField(null=True)
    
    t1=models.CharField(max_length=200, null=True)
    t2=models.CharField(max_length=200, null=True)
    t3=models.CharField(max_length=200, null=True)
    t4=models.CharField(max_length=200, null=True)
    t5=models.CharField(max_length=200, null=True)
    t6=models.CharField(max_length=200, null=True)
    t7=models.CharField(max_length=200, null=True)
    t8=models.CharField(max_length=200, null=True)
    t9=models.CharField(max_length=200, null=True)
    t10=models.CharField(max_length=200, null=True)
    t11=models.CharField(max_length=200, null=True)
    t12=models.CharField(max_length=200, null=True)
    t13=models.CharField(max_length=200, null=True)
    t14=models.CharField(max_length=200, null=True)
    t14_1=models.CharField(max_length=200, null=True)
    t14_2=models.CharField(max_length=200, null=True)
    t14_3=models.CharField(max_length=200, null=True)
    t14_4=models.CharField(max_length=200, null=True)
    t15=models.CharField(max_length=200, null=True)
    t15_1=models.CharField(max_length=200, null=True)
    t15_2=models.CharField(max_length=200, null=True)
    t16=models.CharField(max_length=200, null=True)
    t17=models.CharField(max_length=200, null=True)
    t18=models.CharField(max_length=200, null=True)
    t19=models.CharField(max_length=200, null=True)
    t20=models.CharField(max_length=200, null=True)
    t21=models.CharField(max_length=200, null=True)
    t22=models.CharField(max_length=200, null=True)
    t23=models.CharField(max_length=200, null=True)
    t23_1=models.CharField(max_length=200, null=True)
    t23_2=models.CharField(max_length=200, null=True)
    t23_3=models.CharField(max_length=200, null=True)
    t23_4=models.CharField(max_length=200, null=True)
    t23_5=models.CharField(max_length=200, null=True)
    t24=models.CharField(max_length=200, null=True)
    t24_1=models.CharField(max_length=200, null=True)
    t24_2=models.CharField(max_length=200, null=True)
    t25=models.CharField(max_length=200, null=True)
    t26=models.CharField(max_length=200, null=True)
    t27=models.CharField(max_length=200, null=True)
    t27_1=models.CharField(max_length=200, null=True)
    t27_2=models.CharField(max_length=200, null=True)
    t27_3=models.CharField(max_length=200, null=True)
    t27_4=models.CharField(max_length=200, null=True)
    t27_5=models.CharField(max_length=200, null=True)
    t27_6=models.CharField(max_length=200, null=True)
    t28=models.CharField(max_length=200, null=True)
    t28_1=models.CharField(max_length=200, null=True)
    t28_2=models.CharField(max_length=200, null=True)
    t28_3=models.CharField(max_length=200, null=True)
    t29=models.CharField(max_length=200, null=True)
    t30=models.CharField(max_length=200, null=True)
    t30_1=models.CharField(max_length=200, null=True)
    t30_2=models.CharField(max_length=200, null=True)
    t31=models.CharField(max_length=200, null=True)
    t31_1=models.CharField(max_length=200, null=True)
    t31_2=models.CharField(max_length=200, null=True)
    t31_3=models.CharField(max_length=200, null=True)
    t31_4=models.CharField(max_length=200, null=True)
    t32=models.CharField(max_length=200, null=True)
    t33=models.CharField(max_length=200, null=True)
    t34=models.CharField(max_length=200, null=True)
    t34_1=models.CharField(max_length=200, null=True)
    t34_2=models.CharField(max_length=200, null=True)
    t35=models.CharField(max_length=200, null=True)
    t35_1=models.CharField(max_length=200, null=True)
    t35_2=models.CharField(max_length=200, null=True)
    t36=models.CharField(max_length=200, null=True)
    t36_1=models.CharField(max_length=200, null=True)
    t36_2=models.CharField(max_length=200, null=True)
    t36_3=models.CharField(max_length=200, null=True)
    # t37=models.CharField(max_length=200, null=True)
    t37=models.TextField(null=True)
    # t38=models.CharField(max_length=200, null=True)
    t38=models.TextField(null=True)
    # t39=models.CharField(max_length=200, null=True)
    t39=models.TextField(null=True)
    


# class Echo_payment(models.Model):
#     # patient=models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='echo_payment')
#     created_date = models.DateField(default=timezone.now)
#     created_time = models.TimeField(default=timezone.now)
#     done_by=models.CharField(max_length=200, null=True)
#     amount=models.IntegerField(null=True)