# Generated by Django 4.2.1 on 2023-07-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Med_test1_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reffered_by', models.CharField(max_length=200, null=True)),
                ('validated_by', models.CharField(max_length=200, null=True)),
                ('t1', models.CharField(max_length=200, null=True)),
                ('t2', models.CharField(max_length=200, null=True)),
                ('t3', models.CharField(max_length=200, null=True)),
                ('t4', models.CharField(max_length=200, null=True)),
                ('t5', models.CharField(max_length=200, null=True)),
                ('t6', models.CharField(max_length=200, null=True)),
                ('t7', models.CharField(max_length=200, null=True)),
                ('t8', models.CharField(max_length=200, null=True)),
                ('t9', models.CharField(max_length=200, null=True)),
                ('t10', models.CharField(max_length=200, null=True)),
                ('t11', models.CharField(max_length=200, null=True)),
                ('t12', models.CharField(max_length=200, null=True)),
                ('t13', models.CharField(max_length=200, null=True)),
                ('t14', models.CharField(max_length=200, null=True)),
                ('t15', models.CharField(max_length=200, null=True)),
                ('t16', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
