# Generated by Django 4.2.1 on 2023-07-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_test1_app', '0002_med_test1_report_created_date_med_test1_report_t14_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med_test1_report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
