# Generated by Django 4.2.1 on 2023-07-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_test1_app', '0004_med_test1_report_lab_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med_test1_report',
            name='t37',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='med_test1_report',
            name='t38',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='med_test1_report',
            name='t39',
            field=models.TextField(null=True),
        ),
    ]
