# Generated by Django 4.2.1 on 2023-07-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_test1_app', '0005_alter_med_test1_report_t37_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_test1_report',
            name='t1_1',
            field=models.TextField(null=True),
        ),
    ]
