# Generated by Django 4.2.1 on 2023-07-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_test1_app', '0006_med_test1_report_t1_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_test1_report',
            name='t40',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='med_test1_report',
            name='t40_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='med_test1_report',
            name='t40_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='med_test1_report',
            name='t40_3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
